"""add registration date and region

Revision ID: 00b47d3962d4
Revises: ec74354c7915
Create Date: 2026-06-14 07:49:07.258391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "00b47d3962d4"
down_revision: Union[str, Sequence[str], None] = "ec74354c7915"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("registration_date", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "companies", sa.Column("region", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "region")
    op.drop_column("companies", "registration_date")
    # ### end Alembic commands ###
