"""add profit fields

Revision ID: 37eba05c46dd
Revises: b148d2015934
Create Date: 2026-06-16 12:58:47.760013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37eba05c46dd'
down_revision: Union[str, Sequence[str], None] = 'b148d2015934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('profit_2023', sa.BigInteger(), nullable=True))
    op.add_column('companies', sa.Column('profit_2024', sa.BigInteger(), nullable=True))
    op.add_column('companies', sa.Column('profit_2025', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'profit_2025')
    op.drop_column('companies', 'profit_2024')
    op.drop_column('companies', 'profit_2023')
    # ### end Alembic commands ###
