"""add registration date and region

Revision ID: 547475ba952d
Revises: 00b47d3962d4
Create Date: 2026-06-14 08:14:45.315585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547475ba952d'
down_revision: Union[str, Sequence[str], None] = '00b47d3962d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('revenue_2023', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'revenue_2023')
    # ### end Alembic commands ###
