"""add growth fields to company

Revision ID: 54b4bdc377b6
Revises: 8c865213d9e2
Create Date: 2026-08-25 10:38:12.399687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "54b4bdc377b6"
down_revision: Union[str, Sequence[str], None] = "8c865213d9e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("revenue_growth_3", sa.Float(), nullable=True))
    op.add_column("companies", sa.Column("profit_growth_3", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "profit_growth_3")
    op.drop_column("companies", "revenue_growth_3")
    # ### end Alembic commands ###
