"""add indexes to company

Revision ID: 8c865213d9e2
Revises: cc08795cd50e
Create Date: 2026-08-03 18:43:56.296322

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8c865213d9e2"
down_revision: Union[str, Sequence[str], None] = "cc08795cd50e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_companies_ai_priority"), "companies", ["ai_priority"], unique=False
    )
    op.create_index(
        op.f("ix_companies_ai_risk"), "companies", ["ai_risk"], unique=False
    )
    op.create_index(op.f("ix_companies_region"), "companies", ["region"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_region"), table_name="companies")
    op.drop_index(op.f("ix_companies_ai_risk"), table_name="companies")
    op.drop_index(op.f("ix_companies_ai_priority"), table_name="companies")
    # ### end Alembic commands ###
