"""add is_deleted to companies

Revision ID: c17a37c5f8c6
Revises: ba314abc6730
Create Date: 2026-09-23 16:54:38.851912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c17a37c5f8c6"
down_revision: Union[str, Sequence[str], None] = "ba314abc6730"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_index(
        op.f("ix_companies_is_deleted"), "companies", ["is_deleted"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_is_deleted"), table_name="companies")
    op.drop_column("companies", "is_deleted")
    # ### end Alembic commands ###
