"""add ai fields

Revision ID: cc08795cd50e
Revises: 37eba05c46dd
Create Date: 2026-06-18 12:31:10.648923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc08795cd50e'
down_revision: Union[str, Sequence[str], None] = '37eba05c46dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('ai_priority', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('ai_risk', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'ai_risk')
    op.drop_column('companies', 'ai_priority')
    # ### end Alembic commands ###
