"""add company metrics

Revision ID: cc920dc9f881
Revises: 369963716d74
Create Date: 2026-06-11 21:53:40.263832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cc920dc9f881"
down_revision: Union[str, Sequence[str], None] = "369963716d74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies", sa.Column("revenue_2025", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("revenue_2024", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("tenders_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "companies",
        sa.Column("courts_count", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "courts_count")
    op.drop_column("companies", "tenders_count")
    op.drop_column("companies", "revenue_2024")
    op.drop_column("companies", "revenue_2025")
    # ### end Alembic commands ###
