"""add company contacts

Revision ID: ec74354c7915
Revises: b3f2dee3ebe9
Create Date: 2026-06-13 19:36:39.754421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec74354c7915'
down_revision: Union[str, Sequence[str], None] = 'b3f2dee3ebe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('phone', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'phone')
    # ### end Alembic commands ###
